-- Seed main menu from restaurant menu images: categories and items.
-- Run with: node scripts/seed-main-menu.js
-- Or: psql $DATABASE_URL -f drizzle/0005_seed_main_menu.sql

-- Clear existing menu data (categories and items)
DELETE FROM menu_items;
DELETE FROM menu_categories;

-- Reset sequences so IDs start from 1
ALTER SEQUENCE menu_categories_id_seq RESTART WITH 1;
ALTER SEQUENCE menu_items_id_seq RESTART WITH 1;

-- Insert categories in display order
INSERT INTO menu_categories (name, sort_order) VALUES
  ('Sri Lanka Breakfast', 1),
  ('Fresh Fruit Plate', 2),
  ('Banana Pan Cake', 3),
  ('Omelette', 4),
  ('Sandwich', 5),
  ('Spring Rolls', 6),
  ('Soup', 7),
  ('Fried Rice', 8),
  ('Spaghetti', 9),
  ('Chicken', 10),
  ('Traditional Sri Lankan Rice and Curry', 11),
  ('Noodles', 12),
  ('Salad', 13),
  ('Appetizers', 14),
  ('Fish', 15),
  ('Prawns', 16),
  ('Calamari / Squid', 17),
  ('Dessert', 18),
  ('Side Portion', 19);

-- Insert menu items (name, description, price, category, sort_order)
INSERT INTO menu_items (name, description, price, category, sort_order) VALUES
  ('Strring Hoppers with fish curry or chicken curry with coconut sambol', '', '1000/-', 'Sri Lanka Breakfast', 1),
  ('Coconut Rotti with onion sambol or honey', '', '900/-', 'Sri Lanka Breakfast', 2),
  ('Plain hoppers, egg hopper with onion sambol or butter and sugar', '', '900/-', 'Sri Lanka Breakfast', 3),
  ('Mango, Papaya, Pineapple, Banana, Watermelon', '', '1200/-', 'Fresh Fruit Plate', 4),
  ('Banana, Golden, Syrup, Whipped Cream', '', '1200/-', 'Banana Pan Cake', 5),
  ('Sri Lanka Omelette with Toast', 'Three Eggs, Green Chillie, Tomato, Onion, Pepper, Salt', '750/-', 'Omelette', 6),
  ('Bacon Omelette with Toast', 'Three Eggs, Bacon, Salt, Pepper', '900/-', 'Omelette', 7),
  ('Cheese Omelette with Toast', 'Three Eggs, Cheese', '900/-', 'Omelette', 8),
  ('Fried Egg with Toast', 'Three Eggs, Salt, Pepper', '800/-', 'Omelette', 9),
  ('Scrambled Egg with Toast', 'Three Eggs, Salt, Pepper, Butter, Fresh milk', '850/-', 'Omelette', 10),
  ('Chicken Sandwich', 'Chicken, Toast, Butter, Mustard cream, Salt, Pepper', '1700/-', 'Sandwich', 11),
  ('Tuna Sandwich', 'Mayonnaise, Salt, Onion, Tomato, Toast, Green Chillie', '1800/-', 'Sandwich', 12),
  ('Cheese and Tomato Sandwich', 'Cheese Tomato, Butter, Mayonnaise', '1500/-', 'Sandwich', 13),
  ('Egg Sandwich', 'Mustard Cream, Salt, pepper, Butter, Eggs', '1100/-', 'Sandwich', 14),
  ('Club Sandwich', 'Chicken, Bacon or ham, Cheese, Tomato, Lettuce, Cucumber three pieces, Butter, Coleslaw, Salad, Fries. Every Sandwich served with chips or salad bouquet', '2000/-', 'Sandwich', 15),
  ('Chicken Spring Roll', '', '1000/-', 'Spring Rolls', 16),
  ('Fish Spring Roll', '', '1000/-', 'Spring Rolls', 17),
  ('Vegetable Spring Roll', '', '850/-', 'Spring Rolls', 18),
  ('Cream of Tomato Soup', '', '800/-', 'Soup', 19),
  ('Puree of Pumpkin and Ginger Soup', '', '800/-', 'Soup', 20),
  ('Tom Yum Soup', '', '1500/-', 'Soup', 21),
  ('Seafood Broth', '', '1400/-', 'Soup', 22),
  ('Cream of Lentil Soup', '', '800/-', 'Soup', 23),
  ('Fried Rice with Vegetable', '', '1500/-', 'Fried Rice', 24),
  ('Fried Rice with Prawns', '', '2000/-', 'Fried Rice', 25),
  ('Fried Rice with Chicken', '', '1900/-', 'Fried Rice', 26),
  ('Fried Rice with Sea Food', '', '2000/-', 'Fried Rice', 27),
  ('Indonesian Fried Rice', '', '1700/-', 'Fried Rice', 28),
  ('Fried Rice with Chopsue and Chillie Paste', '', '2200/-', 'Fried Rice', 29),
  ('Spaghetti Pomodoro Basilio', '', '2200/-', 'Spaghetti', 30),
  ('Spaghetti Carbonara', '', '2500/-', 'Spaghetti', 31),
  ('Spaghetti Butter', '', '1600/-', 'Spaghetti', 32),
  ('Spaghetti Arabbitha', '', '2500/-', 'Spaghetti', 33),
  ('Spaghetti Seafood', '', '2500/-', 'Spaghetti', 34),
  ('Spaghetti Vegetarian', '', '2200/-', 'Spaghetti', 35),
  ('Grilled chicken with chips or mash potato and salad with honey mustard sauce', '', '3200/-', 'Chicken', 36),
  ('BBQ chicken with grilled vegetables', '', '3500/-', 'Chicken', 37),
  ('Fish Curry', '', '2000/-', 'Traditional Sri Lankan Rice and Curry', 38),
  ('Chicken Curry', '', '2000/-', 'Traditional Sri Lankan Rice and Curry', 39),
  ('Calamari Curry', '', '2000/-', 'Traditional Sri Lankan Rice and Curry', 40),
  ('Vegetable Curry', 'Three vegetable curries with Traditional accompaniment hot and spicy curry', '1600/-', 'Traditional Sri Lankan Rice and Curry', 41),
  ('Fried Noodles with Chicken', '', '1600/-', 'Noodles', 42),
  ('Fried Noodles with Vegetables', '', '1300/-', 'Noodles', 43),
  ('Mixed Seafood Noodles', '', '1800/-', 'Noodles', 44),
  ('Prawn Noodles', '', '1800/-', 'Noodles', 45),
  ('Green Salad', '', '900/-', 'Salad', 46),
  ('Caesar Salad', '', '2200/-', 'Salad', 47),
  ('Nicoise Salad', 'Tomatoes, Bean, Diced, Potatoes, Salt, Pepper, Vinaigrette, Anchovy Fillets, Capers, Olives', '1900/-', 'Salad', 48),
  ('Threeway tomato salad', '', '1300/-', 'Salad', 49),
  ('Mozzarella Alla Caprese', 'Mozzarella Cheese, Fresh Tomato, Creole pesto, Dry Oregano', '2000/-', 'Appetizers', 50),
  ('Fish Carpaccio with Balsamic Vinegar', 'Yellow fin tuna, Pesto Sauce, Dry Oregano, Balsamic, Vinegar', '1500/-', 'Appetizers', 51),
  ('Prawn tail and pink lemon cocktail', 'Prawns, lemon, olives, cocktail sauce, parsley and lime', '1400/-', 'Appetizers', 52),
  ('Grilled mahi-mahi with mix salad, Chips and ginger sauce', 'Ginger, celery, carrot, onion, garlic, soya sauce, pepper, salt and sesame oil', '3200/-', 'Fish', 53),
  ('Grilled fish with citrus salad, mash potato and optional sauce', 'Sauce options: Garlic butter, lemon butter, ginger sauce', '3100/-', 'Fish', 54),
  ('Poached mahi-mahi with boiled vegetable and optional sauce', '', '3000/-', 'Fish', 55),
  ('Grilled fish with lemon butter sauce and mix salad, mash potato', '', '3200/-', 'Fish', 56),
  ('Grilled Barracuda with mix salad, mash potato accompaniment with orange balsamic reduction sauce', '', '3300/-', 'Fish', 57),
  ('Mixed grilled seafood platter with mixed salad, mashed potato, cocktail sauce, mayonnaise', '', '7400/-', 'Fish', 58),
  ('Spicy BBQ fish with mash potato and salad', '', '3600/-', 'Fish', 59),
  ('Grilled Barracuda with capers mash and salad, garlic butter sauce', '', '3300/-', 'Fish', 60),
  ('Grilled prawns with parsley potato, salad and garlic butter sauce', '', '3900/-', 'Prawns', 61),
  ('Batter fried prawns with mash, salad with cocktail sauce', '', '3900/-', 'Prawns', 62),
  ('Tempura prawns with mango salsa, salad and mash potato', '', '4000/-', 'Prawns', 63),
  ('Devilled prawns with steamed rice', '', '3900/-', 'Prawns', 64),
  ('Garlic butter prawns with steamed rice', '', '3900/-', 'Prawns', 65),
  ('Grilled calamari with capers mash and salad, garlic butter sauce', '', '3900/-', 'Calamari / Squid', 66),
  ('Devilled calamari with steamed rice', '', '4000/-', 'Calamari / Squid', 67),
  ('Fried calamari with garlic mayonnaise sauce salad, mash potato', '', '3900/-', 'Calamari / Squid', 68),
  ('Garlic butter calamari with steamed rice', '', '4000/-', 'Calamari / Squid', 69),
  ('Banana split', '', '1800/-', 'Dessert', 70),
  ('Banana fritters with Ice Cream', '', '1000/-', 'Dessert', 71),
  ('Pine apple fritters with Ice Cream', '', '1100/-', 'Dessert', 72),
  ('Curd and treacle', '', '900/-', 'Dessert', 73),
  ('Choice of Ice Cream', 'Vanilla, Chocolate, Fruit and Nut', '1200/-', 'Dessert', 74),
  ('Fresh Fruit Plate', '', '1200/-', 'Dessert', 75),
  ('Bacon', '', '700/-', 'Side Portion', 76),
  ('Sausages', '', '700/-', 'Side Portion', 77),
  ('Cheese Slices', '', '800/-', 'Side Portion', 78),
  ('French fries bowl', '', '1500/-', 'Side Portion', 79);
